env:
  browser: true
  es6: true
extends:
- 'eslint:recommended'
- 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
globals:
  module: true
rules:
  'react/jsx-uses-react': 1
  'react/jsx-uses-vars': 1
  'react/react-in-jsx-scope': 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
